INSERT INTO 3cbtags VALUES (NULL,'Abbey Beers','abbey-beers',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Alt and Amber Beers','alt-and-amber-beers',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Beers made with Fruit Spices Herbs and Seeds','beers-made-with-fruit-spices-herbs-and-seeds',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Belgian Sour Red Beer','belgian-sour-red-beer',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Belgian style Wheat Beers','belgian-style-wheat-beers',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Best Bitters','best-bitters',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Bieres de Garde','bieres-de-garde',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Bitters','bitters',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Black and Dark Lagers','black-and-dark-lagers',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Bocks','bocks',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Brown and Mild Ales','brown-and-mild-ales',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Dortmunder Export','dortmunder-export',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Extra Strong Beers and Bitters','extra-strong-beers-and-bitters',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Golden Ales','golden-ales',NULL)
INSERT INTO 3cbtags VALUES (NULL,'India Pale Ales','india-pale-ales',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Kölsch','kölsch',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Lambic and Gueuze','lambic-and-gueuze',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Old Ales Barley Wines and Vintage Ales','old-ales-barley-wines-and-vintage-ales',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Pale Ales','pale-ales',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Pale Lagers','pale-lagers',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Pilsners','pilsners',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Porters and Stouts','porters-and-stouts',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Saison','saison',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Scottish Ales','scottish-ales',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Smoked Beer','smoked-beer',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Steam Beer','steam-beer',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Trappist Beers','trappist-beers',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Vienna Red Märzen and Oktoberfest Beers','vienna-red-märzen-and-oktoberfest-beers',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Wheat Beers','wheat-beers',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Australia','australia',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Austria','austria',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Belgium','belgium',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Czech Republic','czech-republic',NULL)
INSERT INTO 3cbtags VALUES (NULL,'England','england',NULL)
INSERT INTO 3cbtags VALUES (NULL,'France','france',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Germany','germany',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Ireland','ireland',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Japan','japan',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Lithuania','lithuania',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Mexico','mexico',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Netherlands','netherlands',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Poland','poland',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Russia','russia',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Scotland','scotland',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Sri Lanka','sri-lanka',NULL)
INSERT INTO 3cbtags VALUES (NULL,'USA','usa',NULL)
INSERT INTO 3cbtags VALUES (NULL,'Wales','wales',NULL)
